# Generated by Django 3.1.5 on 2021-02-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title for Graph')),
                ('min_time', models.IntegerField(verbose_name='Min time for graph')),
                ('max_time', models.IntegerField(verbose_name='Max time for graph')),
                ('file_field', models.FileField(upload_to='', verbose_name='Upload file(s)')),
            ],
        ),
    ]
